### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by HappyLDE** [VasekProchazka/vue3-portal#2]
Thank you for making this! It works perfect.

Can't believe what an oversell was the portal from vue 3 which is kinda useless......

**Comment by dragomirweb** [comment]
just a quick addition, if your not suporting vue2 why not use teleport from vue3?

**Comment by VasekProchazka** [comment]
Hello, I really appreciate you using this library. 

The teleport is design just for scope out of Vue.js
